spring:
  application:
    name: atlas-mountain
  jackson:
    default-property-inclusion: non_null
  flyway:
    locations:
      - classpath:db/migration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
